version: "3.1"
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
      - mariadb:db
    ports: 
      - 8080:80

  wordpress:
    image: wordpress:latest
    links: 
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=mypass
    ports: 
      - 8081:80